run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/cheggaaa/pb/v3
          - github.com/BurntSushi/toml
          - github.com/jackc/pgx/stdlib
          - github.com/jmoiron/sqlx
          - github.com/rabbitmq/amqp091-go
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/app
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/logger
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/server/http
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/storage/memory
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/storage/sql
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/storage
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/server
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/pkg/event_service_v1
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/model
          - github.com/cronnoss/hw-test/hw12_13_14_15_calendar/internal/transport/rabbitmq

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
        - depguard
    - path: \.go
      linters:
        - revive
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
