apiVersion: v2
name: calendar
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: rabbitmq
    version: 0.1.0
    condition: rabbitmq.enabled
  - name: database
    version: 0.1.0
    condition: database.enabled
