[logger]
level = "DEBUG"

[http-server]
host = "localhost"
port = "8090"

[grpc-server]
host = "localhost"
port = "50000"

[storage]
#db = "in_memory"
db = "sql"
dsn = "postgresql://root:secretkey@localhost:5432/calendar?sslmode=disable"
