apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range $key, $value := .Values.envs }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - exec pg_isready --host localhost --dbname $POSTGRES_DB --username $POSTGRES_USER --timeout 2
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - exec pg_isready --host localhost --dbname $POSTGRES_DB --username $POSTGRES_USER --timeout 2
            initialDelaySeconds: 30
            periodSeconds: 10
