apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: {{ .Values.imageInit.repo }}:{{ .Values.imageInit.tag }}
          command:
            - '/bin/sh'
            - '-c'
            - >
              until nc -z postgres 5432; do
                echo 'Waiting for postgres service to be ready...';
                sleep 2;
              done
        - name: wait-for-rabbitmq
          image: {{ .Values.imageInit.repo }}:{{ .Values.imageInit.tag }}
          command:
            - '/bin/sh'
            - '-c'
            - >
              until nc -z rabbitmq 5672; do
                echo 'Waiting for rabbitmq service to be ready...';
                sleep 2;
              done
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
            - containerPort: {{ .Values.containerPort2 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
